### ISSUE TITLE
SetResolver::detectFromNameAndDirectory() must be of the type string, boolean returned

### ISSUE THREAD

**Issue by escopecz** [rectorphp/rector-prefixed#3]
I can install Rector-prefixed fine into a project:

```bash
$ composer require rector/rector-prefixed:@dev --dev
```
I can run the Rector help also fine:

```bash
$ bin/rector
Rector 0.6.x-dev@659aa92
...
```

But when I give it some work to do, it fails like this:
```bash
$ bin/rector.phar process app --set dead-code --dry-run
 [ERROR] Return value of _HumbugBoxda341487b1a2\Symplify\SetConfigResolver\SetResolver::detectFromNameAndDirectory()    
         must be of the type string, boolean returned
```

I saw that you tried to resolve this with https://github.com/Symplify/SetConfigResolver/commit/317aa6642d89028c338decbd4651feb1bd325527 and then you released [v7.1.0](https://github.com/Symplify/SetConfigResolver/releases/tag/v7.1.0) but I don't see this package as a [direct dependency of Rector](https://github.com/rectorphp/rector/blob/master/composer.json). Is that change part of Rector or not yet?

**Comment by TomasVotruba** [comment]
This should be right here: https://github.com/rectorphp/rector/blob/9a330e28544871196b3a3c929905981f3c008177/composer.json#L32

If you unpack the phar, what version of SteConfigResolver is there?

**Comment by escopecz** [comment]
Good idea. I cannot see composer.json nor composer.lock in the extracted phar so I checked the file directly and it does not contain the change. It still has `return $nearestMatch->getRealPath();`

**Comment by TomasVotruba** [comment]
I've triggered the PHAR build: https://travis-ci.org/rectorphp/rector/builds/622898345
Let's see

**Comment by TomasVotruba** [comment]
This should be fixed already, forgot to close
