### ISSUE TITLE
v0.6.7 tag

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector-prefixed#4]
Hey @TomasVotruba ! Any chance you could tag a v0.6.7 ? Which had me wondering if it would be possible to make tagging of `rector-prefixed` automatic whenever a tag of `rector` is created ?

**Comment by TomasVotruba** [comment]
Hey, it should work, just on last tag there was broken syntax:
https://github.com/rectorphp/rector/commit/f28ddd0773d14d9df236bb7fb694d0dec4fbe74c

I'll tag it manually now

**Comment by TomasVotruba** [comment]
Here you go https://github.com/rectorphp/rector-prefixed/releases/tag/v0.6.7

**Comment by gnutix** [comment]
Thanks! However, running `php rector.phar -v` still gives `Rector 0.6.x-dev@5ce4357` instead of a nice `Rector 0.6.7`. Would it be hard to do ?

**Comment by TomasVotruba** [comment]
I'm not very skilled at this build. I'm happy it pushes phar here.

But if you find a way, feel free to send PR.

Here is the phar build: https://github.com/rectorphp/rector/blob/master/.travis.yml#L35
