### ISSUE TITLE
Remove stubs/ from rector.phar

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector-prefixed#5]
Would it be possible to remove the stubs/ folder from rector.phar to prevent PHPStorm multiple definition for classes (without having to exclude the whole phar from the project, which is useful to investigate Rectors) ?

**Comment by TomasVotruba** [comment]
Sure, it should not be there

**Comment by TomasVotruba** [comment]
Btw, better create issues/PRs in main Rector repository, as this is read-only
